"""instance_type to gpu_type

Revision ID: e76576aecaaf
Revises: e1fcd03a5554
Create Date: 2026-03-18 19:55:33.032386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76576aecaaf'
down_revision: Union[str, None] = 'e1fcd03a5554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instance_types', 'gpu_type_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instance_types', 'gpu_type_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
