"""add family, memory_gb, variant to gpu_types

Revision ID: c0b7b7232c64
Revises: 240dffa35894
Create Date: 2026-03-18 17:33:32.946147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b7b7232c64'
down_revision: Union[str, None] = '240dffa35894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpu_types', sa.Column('family', sa.String(), nullable=False))
    op.add_column('gpu_types', sa.Column('memory_gb', sa.Integer(), nullable=False))
    op.add_column('gpu_types', sa.Column('variant', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gpu_types', 'variant')
    op.drop_column('gpu_types', 'memory_gb')
    op.drop_column('gpu_types', 'family')
    # ### end Alembic commands ###
