"""instance_type add instance_family

Revision ID: da43da950248
Revises: 682368304bc9
Create Date: 2026-03-19 10:35:14.382029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da43da950248'
down_revision: Union[str, None] = '682368304bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance_types', sa.Column('instance_family', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance_types', 'instance_family')
    # ### end Alembic commands ###
