"""add to tem details

Revision ID: b589236725bf
Revises: 49866e499a35
Create Date: 2026-03-24 11:58:37.703608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b589236725bf"
down_revision: Union[str, None] = "49866e499a35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("account_id", sa.String(), nullable=True))
    op.add_column("teams", sa.Column("account_name", sa.String(), nullable=True))
    op.add_column("teams", sa.Column("cost_center", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "cost_center")
    op.drop_column("teams", "account_name")
    op.drop_column("teams", "account_id")
    # ### end Alembic commands ###
