"""add uuid format constraint to gpus

Revision ID: 34ad85768b33
Revises: f9b5007f8b64
Create Date: 2026-03-18 18:49:54.789313

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34ad85768b33"
down_revision: Union[str, None] = "f9b5007f8b64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "gpu_uuid_format",
        "gpus",
        "uuid ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("gpu_uuid_format", "gpus", type_="check")
    # ### end Alembic commands ###
