"""remove model name from gpu

Revision ID: f9b5007f8b64
Revises: 859d57d3525e
Create Date: 2026-03-18 18:34:57.962645

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f9b5007f8b64"
down_revision: Union[str, None] = "859d57d3525e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gpus", "model_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gpus", sa.Column("model_name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
