"""initial schema

Revision ID: 240dffa35894
Revises:
Create Date: 2026-03-13 14:32:09.859699

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "240dffa35894"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocation_types",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_allocation_types_name"), "allocation_types", ["name"], unique=False)
    op.create_table(
        "clouds", sa.Column("name", sa.String(), nullable=False), sa.PrimaryKeyConstraint("name")
    )
    op.create_index(op.f("ix_clouds_name"), "clouds", ["name"], unique=False)
    op.create_table(
        "gpu_types", sa.Column("name", sa.String(), nullable=False), sa.PrimaryKeyConstraint("name")
    )
    op.create_index(op.f("ix_gpu_types_name"), "gpu_types", ["name"], unique=False)
    op.create_table(
        "teams", sa.Column("name", sa.String(), nullable=False), sa.PrimaryKeyConstraint("name")
    )
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=False)
    op.create_table(
        "workload_types",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_workload_types_name"), "workload_types", ["name"], unique=False)
    op.create_table(
        "instance_types",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cloud_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cloud_name"],
            ["clouds.name"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_instance_types_name"), "instance_types", ["name"], unique=False)
    op.create_table(
        "owners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("team_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_name"],
            ["teams.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_owners_email"), "owners", ["email"], unique=True)
    op.create_index(op.f("ix_owners_id"), "owners", ["id"], unique=False)
    op.create_table(
        "gpu_clusters",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cloud_name", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cloud_name"],
            ["clouds.name"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owners.id"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_gpu_clusters_name"), "gpu_clusters", ["name"], unique=False)
    op.create_table(
        "gpu_nodes",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cluster_name", sa.String(), nullable=False),
        sa.Column("instance_type_name", sa.String(), nullable=False),
        sa.Column("team_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_name"],
            ["gpu_clusters.name"],
        ),
        sa.ForeignKeyConstraint(
            ["instance_type_name"],
            ["instance_types.name"],
        ),
        sa.ForeignKeyConstraint(
            ["team_name"],
            ["teams.name"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_gpu_nodes_name"), "gpu_nodes", ["name"], unique=False)
    op.create_table(
        "cost_timeseries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("node_name", sa.String(), nullable=False),
        sa.Column("instance_type_name", sa.String(), nullable=False),
        sa.Column("workload_type_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instance_type_name"],
            ["instance_types.name"],
        ),
        sa.ForeignKeyConstraint(
            ["node_name"],
            ["gpu_nodes.name"],
        ),
        sa.ForeignKeyConstraint(
            ["workload_type_name"],
            ["workload_types.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cost_timeseries_date"), "cost_timeseries", ["date"], unique=False)
    op.create_index(op.f("ix_cost_timeseries_id"), "cost_timeseries", ["id"], unique=False)
    op.create_index(
        op.f("ix_cost_timeseries_node_name"), "cost_timeseries", ["node_name"], unique=False
    )
    op.create_table(
        "gpus",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("gpu_number", sa.Integer(), nullable=False),
        sa.Column("gpu_cluster", sa.String(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("node_name", sa.String(), nullable=True),
        sa.Column("gpu_type_name", sa.String(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("first_discovered", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gpu_type_name"],
            ["gpu_types.name"],
        ),
        sa.ForeignKeyConstraint(
            ["node_name"],
            ["gpu_nodes.name"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_gpus_gpu_cluster"), "gpus", ["gpu_cluster"], unique=False)
    op.create_index(op.f("ix_gpus_uuid"), "gpus", ["uuid"], unique=False)
    op.create_table(
        "allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gpu_uuid", sa.String(), nullable=False),
        sa.Column("team_name", sa.String(), nullable=False),
        sa.Column("workload_type_name", sa.String(), nullable=False),
        sa.Column("allocation_type_name", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["allocation_type_name"],
            ["allocation_types.name"],
        ),
        sa.ForeignKeyConstraint(
            ["gpu_uuid"],
            ["gpus.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["team_name"],
            ["teams.name"],
        ),
        sa.ForeignKeyConstraint(
            ["workload_type_name"],
            ["workload_types.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_allocations_end_time"), "allocations", ["end_time"], unique=False)
    op.create_index(op.f("ix_allocations_gpu_uuid"), "allocations", ["gpu_uuid"], unique=False)
    op.create_index(op.f("ix_allocations_id"), "allocations", ["id"], unique=False)
    op.create_index(op.f("ix_allocations_start_time"), "allocations", ["start_time"], unique=False)
    op.create_index(op.f("ix_allocations_team_name"), "allocations", ["team_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_allocations_team_name"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_start_time"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_id"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_gpu_uuid"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_end_time"), table_name="allocations")
    op.drop_table("allocations")
    op.drop_index(op.f("ix_gpus_uuid"), table_name="gpus")
    op.drop_index(op.f("ix_gpus_gpu_cluster"), table_name="gpus")
    op.drop_table("gpus")
    op.drop_index(op.f("ix_cost_timeseries_node_name"), table_name="cost_timeseries")
    op.drop_index(op.f("ix_cost_timeseries_id"), table_name="cost_timeseries")
    op.drop_index(op.f("ix_cost_timeseries_date"), table_name="cost_timeseries")
    op.drop_table("cost_timeseries")
    op.drop_index(op.f("ix_gpu_nodes_name"), table_name="gpu_nodes")
    op.drop_table("gpu_nodes")
    op.drop_index(op.f("ix_gpu_clusters_name"), table_name="gpu_clusters")
    op.drop_table("gpu_clusters")
    op.drop_index(op.f("ix_owners_id"), table_name="owners")
    op.drop_index(op.f("ix_owners_email"), table_name="owners")
    op.drop_table("owners")
    op.drop_index(op.f("ix_instance_types_name"), table_name="instance_types")
    op.drop_table("instance_types")
    op.drop_index(op.f("ix_workload_types_name"), table_name="workload_types")
    op.drop_table("workload_types")
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_gpu_types_name"), table_name="gpu_types")
    op.drop_table("gpu_types")
    op.drop_index(op.f("ix_clouds_name"), table_name="clouds")
    op.drop_table("clouds")
    op.drop_index(op.f("ix_allocation_types_name"), table_name="allocation_types")
    op.drop_table("allocation_types")
    # ### end Alembic commands ###
