"""add kebab-case constraint to gpu_types.name

Revision ID: 859d57d3525e
Revises: c0b7b7232c64
Create Date: 2026-03-18 18:21:38.209196

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "859d57d3525e"
down_revision: Union[str, None] = "c0b7b7232c64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gpu_types", sa.Column("display_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gpu_types", "display_name")
    # ### end Alembic commands ###
