"""add gpu_type relationship to instance_types

Revision ID: e1fcd03a5554
Revises: 9f351a9017ee
Create Date: 2026-03-18 19:41:33.619183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fcd03a5554'
down_revision: Union[str, None] = '9f351a9017ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance_types', sa.Column('gpu_type_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'instance_types', 'gpu_types', ['gpu_type_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instance_types', type_='foreignkey')
    op.drop_column('instance_types', 'gpu_type_name')
    # ### end Alembic commands ###
