"""gpu_node add allocation

Revision ID: 49866e499a35
Revises: da43da950248
Create Date: 2026-03-19 13:13:12.146348

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "49866e499a35"
down_revision: Union[str, None] = "da43da950248"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("allocations", sa.Column("node_name", sa.String(), nullable=False))
    op.drop_index(op.f("ix_allocations_gpu_uuid"), table_name="allocations")
    op.create_index(op.f("ix_allocations_node_name"), "allocations", ["node_name"], unique=False)
    op.drop_constraint(op.f("allocations_gpu_uuid_fkey"), "allocations", type_="foreignkey")
    op.create_foreign_key(None, "allocations", "gpu_nodes", ["node_name"], ["name"])
    op.drop_column("allocations", "gpu_uuid")
    op.drop_constraint(
        op.f("cost_timeseries_instance_type_name_fkey"), "cost_timeseries", type_="foreignkey"
    )
    op.drop_column("cost_timeseries", "instance_type_name")
    op.add_column("gpu_nodes", sa.Column("region", sa.String(), nullable=True))
    op.alter_column("gpu_nodes", "cluster_name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("gpu_nodes", "cluster_name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("gpu_nodes", "region")
    op.add_column(
        "cost_timeseries",
        sa.Column("instance_type_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("cost_timeseries_instance_type_name_fkey"),
        "cost_timeseries",
        "instance_types",
        ["instance_type_name"],
        ["name"],
    )
    op.add_column(
        "allocations", sa.Column("gpu_uuid", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "allocations", type_="foreignkey")
    op.create_foreign_key(
        op.f("allocations_gpu_uuid_fkey"), "allocations", "gpus", ["gpu_uuid"], ["uuid"]
    )
    op.drop_index(op.f("ix_allocations_node_name"), table_name="allocations")
    op.create_index(op.f("ix_allocations_gpu_uuid"), "allocations", ["gpu_uuid"], unique=False)
    op.drop_column("allocations", "node_name")
    # ### end Alembic commands ###
