"""enforce uuid on gpus

Revision ID: 9f351a9017ee
Revises: 34ad85768b33
Create Date: 2026-03-18 19:13:43.963048

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9f351a9017ee"
down_revision: Union[str, None] = "34ad85768b33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("gpus", "gpu_type_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("gpus", "gpu_type_name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
