"""instance_type to gpu_count

Revision ID: 682368304bc9
Revises: e76576aecaaf
Create Date: 2026-03-19 10:13:02.735822

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "682368304bc9"
down_revision: Union[str, None] = "e76576aecaaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("instance_types", sa.Column("gpu_count", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instance_types", "gpu_count")
    # ### end Alembic commands ###
